services:

  # 1. Zookeeper service
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000 # Basic timing unit (heartbeat interval between Zookeeper servers and clients (like Kafka).
    networks:
      - appointment-network

  # 2. kafka service
  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - appointment-network

  appointment-db:

    image: mysql:8.0
    container_name: appointment-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: doctor_appointment
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword


    volumes:
      - mysql_data:/var/lib/mysql

    ports:
      - "3305:3306"
    networks:
      - appointment-network

  eureka-server:
    build:
      dockerfile: dockerfile
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - appointment-network

  gateway-service:
    build:
      dockerfile: dockerfile
      context: ./gateway-service
    container_name: gateway-service
    environment:
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - appointment-network

  user-service:
    build:
      dockerfile: dockerfile
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - appointment-db
      - eureka-server
    env_file:
      - ./user-service.env
    networks:
      - appointment-network

  # appointment-service
  # notifcation-service
  # payment-service

volumes:
  mysql_data:

networks:
  appointment-network:
    driver: bridge
